### ISSUE TITLE
debug_key is cleared when fetch

### ISSUE THREAD

**Issue by k-o-ta** [WICG/attribution-reporting-api#1133]
debug_key is cleared when using ARA with fetch.
Here are steps to reproduce.

### 1. Steps that debug_key is working.
- Open a new tab and developertools.
- Visit `https://dyn-advertiser-judicious-efficient-pot.glitch.me/test/ara-trigger-attributionsrc.html`

Cookies in the request are like below.
> <img width="1301" alt="image" src="https://github.com/WICG/attribution-reporting-api/assets/5237032/2928abfb-97cc-4578-9a19-f90a51727615">    

Cookies in the Application tab are like below.
> <img width="1304" alt="image" src="https://github.com/WICG/attribution-reporting-api/assets/5237032/a73be556-4a9b-4abd-bf0c-5298d6e0a12c">    

The debug_key is like this. It looks available.
> <img width="1250" alt="image" src="https://github.com/WICG/attribution-reporting-api/assets/5237032/9d7fbbc1-0d33-450b-bf3c-6aa7db7006c5">           

### 2. Steps that debug_key is cleared.
- Show the tab opened on step1 and clear the cookies.
- Visit `https://dyn-advertiser-judicious-efficient-pot.glitch.me/test/ara-trigger-fetch.html`

Cookies in the request are like below.
> <img width="1311" alt="image" src="https://github.com/WICG/attribution-reporting-api/assets/5237032/a20213b0-c28d-44ce-beba-07872c8f2b5e">

Cookies in the Application tab are like below. Cookies are not set. 
> <img width="1121" alt="image" src="https://github.com/WICG/attribution-reporting-api/assets/5237032/94ecde10-2ff9-49c4-93f2-370ee06b5c6e">

The debug_key is like below. It looks cleared.
> <img width="1284" alt="image" src="https://github.com/WICG/attribution-reporting-api/assets/5237032/d297a02c-b690-4318-a5d2-ed603c1f3fa5">

Step2 uses fetch to use AttributionReportingAPI following the [Explainer](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#triggering-attribution).
I expect debug_key to be enabled in the step2.

**Comment by apasel422** [comment]
Thanks for the report.

Since this issue isn't really related to the specification or API in general, in the future please consider asking for help at https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support instead.

That said, this is working as expected, since, as indicated by your comment `Cookies in the Application tab are like below. Cookies are not set.`, the `ar_debug` cookie isn't actually being stored, despite being present in the response.

The cookie isn't being stored because the `fetch` call does not set the proper [`credentials`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials) option, causing it to default to `same-origin`, but this is a cross-origin request.

**Comment by k-o-ta** [comment]
Thank you for your answer.
I set the credential option and stored the cookie as you said. 
Now the debug_key is working.
