### ISSUE TITLE
Spec unintentionally coalesces ARA registration headers

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#1202]
In https://wicg.github.io/attribution-reporting-api/#process-an-attribution-eligible-response we call https://fetch.spec.whatwg.org/#concept-header-list-get, but that algorithm "coalesces" the given header when it appears multiple times in a response. In particular, the individual values are joined by `, `.

Because our headers contain JSON, this almost always results in an invalid value, though it ends up having weird edge cases like

```http
Attribution-Reporting-Register-Source: {"destination":["https://a.test"
Attribution-Reporting-Register-Source: "https://b.test"]}
```
that end up working.

We never intended this, and we should consider making our headers non-coalescing, and either explicitly allowing multiple instances per response, allowing only the first and dropping any additional, or rejecting all if there are multiple.

**Comment by domenic** [comment]
I am worried that this change works against the semantics of HTTP, which say that the multi-header and single-header-with-comma forms are equivalent. And in particular HTTP assumes that intermediaries can split or combine as necessary.

The reason the Fetch spec created high-level helpers which normalize this for you, is to ensure that the whole web platform behaves uniformly in this regard. Adding a special exception for your API seems problematic.

/cc @annevk @mnot to give more context.

**Comment by mnot** [comment]
Yes - HTTP software (intermediaries, client APIs, server APIs) can and will coalesce headers with the same name, and there isn't a way to guarantee this won't happen on the open Internet. This is one of the reasons JSON doesn't work well in headers.

**Comment by mnot** [comment]
`Set-Cookie` is an exception in the protocol; there won't be any more added. See:

  https://httpwg.org/specs/rfc9110.html#field.lines

In particular:

> A recipient MAY combine multiple field lines within a field section that have the same field name into one field line, without changing the semantics of the message, by appending each subsequent field line value to the initial field line value in order, separated by a comma (",") and optional whitespace ([OWS](https://httpwg.org/specs/rfc9110.html#whitespace), defined in [Section 5.6.3](https://httpwg.org/specs/rfc9110.html#whitespace)). For consistency, use comma SP.

Because a recipient may not know the semantics of your field (for example, in an intermediary or generic server library), you can't stop this from happening reliably. 

You _can_ specify that a field only has one value -- if there's more than one `Date`, for example, it's syntactically invalid and so is ignored.

If your field value allows multiple, comma-separated values (which JSON does, depending on the schema), people will split is across multiple field instances, because that's very common practice. So, in short, it's not recommended to specify a syntax which doesn't take coalescing into account.
