### ISSUE TITLE
No Authentication methods listed for requests to /.well-known/attribution-reporting URLs

### ISSUE THREAD

**Issue by mdrapermo** [WICG/attribution-reporting-api#1233]
There is no mention of how to authenticate the requests coming into the `/.well-known/attribution-reporting...` URLs. What will stop bad actors from spamming valid reports they collect from `chrome://attribution-internals` to these endpoints? 

What type of authentication will be supported?

**Comment by jolynyao** [comment]
Hi @mdrapermo, thanks for filing this issue. 
We have been thinking about this type of attack (prevent “reports out of thin air”):
For event-level reports, there should be some server-side authentication on a valid source_event_id
For aggregatable reports, we added the [trigger context_id field](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#optional-reduce-report-delay-with-trigger-context-id) and similarly, there should be some server-side authentication to validate context IDs

If the above can be validated server-side, then the scope of the attack is limited to cases in which the browser user can view HTTP(S) traffic and therefore observe source/trigger registrations to mint valid source_event_ids and trigger context_ids (the use of attribution-internals isn’t required and doesn’t increase the attack surface). For this, we felt that if the browser user wants to pull off an attack, validating reports sent from that user is not sufficient as the registrations themselves may also be compromised.

You can also see the [report verification FAQ](https://github.com/WICG/attribution-reporting-api/blob/main/report_verification.md#faq) for more details, though note that we have decided to ship the trigger context_id field instead of the report verification proposal.

**Comment by mdrapermo** [comment]
@jolynyao Thank you for the information about server side validation of the reports.

 I can't seem to find any mention of `trigger_context_id` field in https://developers.google.com/privacy-sandbox/relevance/attribution-reporting docs. Is this a feature that already exists or is in the works?

**Comment by jolynyao** [comment]
It's currently supported, you can use the documentation here: https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#optional-reduce-report-delay-with-trigger-context-id

We'll work on updating the developers site as well!

**Comment by mdrapermo** [comment]
Awesome! Thank you for the clarification and for your help.
