### ISSUE TITLE
attrbutionsrc element for API

### ISSUE THREAD

**Issue by danieldansker** [WICG/attribution-reporting-api#1472]
Hey,
We are attempting to integrate attribution reporting for our API clients.
This means that we don't have any code on the page and only return click-links for the account to implement on their page.
Is the <attributionsrc> mandatory for the registration of a "attribution source"?
Is it enough for us to respond with the correct header on the request  (Attribution-Reporting-Register-Source)?
Thanks

**Comment by apasel422** [comment]
An HTTP response is eligible to register triggers without opt-in, but in order to [register sources](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#registering-attribution-sources), the request has to be considered eligible, which can be achieved with one of the following:

- `<a attributionsrc>`: can register navigation sources
- `<img attributionsrc>`: can register event sources or triggers
- `<script attributionsrc>`: can register event sources or triggers
- `open(..., ..., 'attributionsrc')`: can register navigation sources
- `fetch(..., {attributionReporting: {eventSourceEligible: true, triggerEligible: false}})`: can register some combination of event sources depending on the given options

An eligible request will contain an `Attribution-Reporting-Eligible` header indicating which types of registrations the response can produce, if any.

**Comment by danieldansker** [comment]
Thanks, @apasel422,
I'm not sure if any of these solutions would work for us. Here’s our use case:  

1. The client sends a GET request for items, and we respond with a list of links they can integrate into their app.  
2. When a user clicks one of these links, we return an HTML document that redirects the user to the landing page (destination).  

I couldn’t determine from the documentation whether the `fetch` can help us registering navigation-source.

**Comment by apasel422** [comment]
> I couldn’t determine from the documentation whether the `fetch` can help us registering navigation-source.

`fetch` isn't capable of registering navigation sources, no.

**Comment by apasel422** [comment]
Feel free to re-open if you have further questions.
