### ISSUE TITLE
Aggregate API: encoding of events (with a small example)

### ISSUE THREAD

**Issue by alois-bissuel** [WICG/attribution-reporting-api#154]
Hello,

Thanks again for the introduction of the [attribution reporting API with aggregate reports.](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md). Although it is already nicely detailed, at Criteo we have a hard time figuring out if our understanding of the API is correct, especially in some of the subtleties out there.
 
I believe the best way to check this (and not take too much time for everyone) would be a small "real-world" example of the usage of the API, roughly from start to finish. It might even help other people to understand how the API can be used.
So here it is:

This is a really small world example, so we scaled down everything. In particular, the histogram is on 5 bits, and L1 is 2^3.
Also, this example is for ad-tech, which we know best.

Let's say we (an ad-tech company) want to measure the conversion of people who clicked on an add on `news.com` which redirected them to a shoe retailer `shoes.com`. We are interested in the number of items bought.
We run 4 campaigns for this retailer on `news.com`, two are video ads, two are clickable items ads. 
We want to measure the efficacy of the campaigns based on the ad placement (here two choices only, top of the web page or not). Finally, we include the price we paid for the ads discretized on 2 bits.
The encoding of the bucket would look like this:

Field  | is_video | campaign_id | is_top_of_page | ad_price_bit_1 | ad_price_bit_2
-----  | ---- | ---- | --- | --- | ---
**Explanation** | campaign type | campaign number | ad placement | ad price | ad price

Because we expect one user to convert only once per week, we will use the full 3 bits of L1 for the value to store in the histogram. This way, we store on 3 bits the number of items bought.
Let's say one user saw a video ad (campaign 0) on top of one page in `news.com`, and this ad's price was high. He converted buying 2 pairs of shoes, so the contribution will be equal to two.

We are not sure on how to encode this sale: basically, we have two understanding which are not aligned.
The first one is that we encode directly the sale in one bucket , ie the output of `processAggregate` (as defined [here](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#attribution-trigger-registration)) is [(10111, 2)]. 

The second one is that for each feature we are interested in, we add to the "one-hot encoded" bucket the value. In other words, bucket 0 would be for is_video=0, bucket 1 for is_video=1, bucket 2 for campaign_id = 0, bucket 3 for campaign_id=1, etc.
Thus, it would look like [(is_video=1, mapped to bucket_id 1, 2), (campaign_id =0, mapped to bucket_id 2, 2), (is_top_page = True, mapped to bucket_id 5, 2), (ad_price_is_high, mapped at bucket 7, 2), (ad_price_is_very_high, mapped at bucket 9, 2)]. Note here that we encode only the features, using the first 10 bucket., if we wanted to add cross feature, we could then fill up to 2^5 buckets.

**Now the question is how to get reports on these encodings.** 

The first one (where the sale is encoded as [(10111, 2)]) will give us all possible crosses (up to 2^5 in this example) when they are filled. We will be able to get the projections on a single feature by summing all (non-zero) buckets with that feature, at the expense of an extremely high noise level. 
Would it be possible to get queries on a bit mask instead of the full tree? 

For the second understanding (where the sale is encoded as [0,2,2,0,2,0,2,0,2,0,2,0....]), one query only will be needed, asking for the first 10 keys. 
Our understanding is, in that case, that the L1 contribution of this sale is 10 which is above of 2^3 = 8, and therefore, this sale would be dropped? Instead of encoding 2 we would need to use a lower value as it contributes to many buckets?

Could you please tell us which understanding is correct?
I hope the example and our questions are clear, feel free to ask for further details or explanation.

**Comment by maudnals** [comment]
Thanks @alois-bissuel!
@johnivdel Can you comment on which understanding is correct?

**Comment by johnivdel** [comment]
> Would it be possible to get queries on a bit mask instead of the full tree?

The current [proposal](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#high-level-two-party-flow) supports querying any n-bit prefix of the histogram, but not a bit mask.

`Rather than returning the full output domain, reporters can ask the processing origins for sums over any bit-prefix of the output domain. This allows us to implement a “hierarchy of histograms”.`

I think the data model you are proposing here could potentially be represented as a hierarchy:

Layer 1 (is_video)
Layer 2 (is_top_of_page)
Layer 3 (ad_price bit 1)
Layer 4 (ad_price bit 2)
Layer 5(campaign_id bit 1)
...

If we look at the [Query Model](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#example-query-model), the histogram for prefix 1 (the first layer) in your example would look like:

[
  {
    "prefix_length": 1,
    "histogram": {0: 0, 1: 2}, //bucket 0 is is_video=0, bucket 1 is is_video=1
  }
]

This way it's possible to get the "feature projection" for is_video without consuming additional L1 budget, and without aggregating multiple noised buckets manually.

You can do this at each layer of the hierarchy, e.g. prefix 2 is the `is_video x is_top_of_page` projection.

However, if you are also interested in a hierarchy where is_top_of_page is at the top (or ad_price bit 1, etc.), then a single hierarchy is not sufficient. Could you clarify if this is the case?

In that case, I think your two options above are fairly accurate:
 - sum across the buckets in Layer 2 to get the is_top_of_page projection (this will be less noisy than summing across Layer 5, but this gets worse as the feature projection moves down the hierarchy)
 - allocate a separate region of the histogram to represent the is_top_of_page hierarchy and consume additional L1

@csharrison to correct me if I missed anything

**Comment by alois-bissuel** [comment]
Thanks @johnivdel for your answer.
Regarding your question on hierarchies, we think that one hierarchy is not sufficient, as our data is not hierarchical in itself.
As highlighted in our simple example (with ad_price and is_top_of_page), there is no a priori link between auction price and ad position. 
There are a few variables which are inherently hierarchical (there is one crafted instance in my example), but it is the exception rather than the norm.

**Comment by alois-bissuel** [comment]
Closing as the n-bit prefix system is no longer included in the current proposal of the API
