### ISSUE TITLE
A few questions about attribution

### ISSUE THREAD

**Issue by nchrys** [WICG/attribution-reporting-api#23]
I have a few questions about attribution mechanisms resulting from this proposal:

- Today advertisers often rely on several marketing channels, often operated by different ad-tech companies. A scenario can be a customer acquisition campaign (metric: cost of acquisition of new buyers), with an additional re-engagement campaign (metric: cost / targeted buyers). In this case a conversion can be attributed to clicks from several different ad-tech companies. So in the framework of this proposal there would be _several clicks with a score of 100_ for a conversion, but each belonging to a _different reporting domain_. Could you clarify if the constraint of having sum of attribution scores to be 100 is for reporting domains separately or across all reporting domains?

- In the proposal it seems the attribution is completely owned by the browser, could you clarify how you handle cases where advertisers have their own special attribution mechanism (happens quite often) and more importantly what happens when several browsers implement different attribution schemes? This will almost surely break the ML models of ad-tech companies.

- About multi-touch attribution and information leak: the proposal says that models other than last-click potentially leak more cross-site information, but I fail to understand this affirmation since even with a last-click attribution negative reports are still sent (reports from impressions with a 0 score of attribution)

**Comment by johnivdel** [comment]
> Could you clarify if the constraint of having sum of attribution scores to be 100 is for reporting domains separately or across all reporting domains?

This constraint is per conversion registration event, which is keyed by reporting domain. While it is possible for there to be multiple clicks with score 100 for a "conversion" from the advertisers point of view, there need to be multiple conversion registrations by the advertiser page for this to occur.

> In the proposal it seems the attribution is completely owned by the browser, could you clarify how you handle cases where advertisers have their own special attribution mechanism (happens quite often)

For attribution in this case, are you referring to how the `attribution_credit` gets assigned to each report? We don’t currently have a carve out for this in the explainer because of the potential information leak and increase in API surface/complexity. Could you give an example of a special attribution scheme?

> and more importantly what happens when several browsers implement different attribution schemes? This will almost surely break the ML models of ad-tech companies.

In an ideal world we could get browsers to agree on an attribution scheme for this interoperability. If browsers are implementing separate variations of attribution, it seems reasonable to have ad-tech model different browsers separately, or fallback to a simpler attribution scheme such as last-click when a browser is providing more data for a cross-browser model (such as in this explainer).

> About multi-touch attribution and information leak: the proposal says that models other than last-click potentially leak more cross-site information, but I fail to understand this affirmation since even with a last-click attribution negative reports are still sent (reports from impressions with a 0 score of attribution)

While all reports are still sent, they are not link-able to each other. If you had an attribution model such as linear, where each click received 1 / N credit for a conversion that had N associated clicks, each report now reveals the number of impressions a user saw prior to a conversion. This information is not easily recoverable with last-click attribution, as you have collisions on conversion metadata from separate conversion flows preventing you from associating these events together.

**Comment by nchrys** [comment]
Thanks for this detailed response.

> This constraint is per conversion registration event, which is keyed by reporting domain.

Understood. I think we can expect most advertisers to rely on several adtech companies and thus they will register multiple conversions. I would like to point out that advertisers today rely on a "cross-reporting domain" view for their attribution, which is quite different from what is proposed here.

> are you referring to how the attribution_credit gets assigned to each report? 

Yes exactly.

> Could you give an example of a special attribution scheme?

There is of course the last-click attribution, uniform attribution (your example of 1/N credit for a conversion that has N associated clicks), and also more exotic attribution schemes such as not considering clicks one hour after a first click leads to a landing page. Today advertisers have a lot of freedom in how they define their attribution.

> it seems reasonable to have ad-tech model different browsers separately

Understood.

> or fallback to a simpler attribution scheme such as last-click when a browser is providing more data for a cross-browser model (such as in this explainer).

Sorry I fail to understand, could you provide more details for this case?

> While all reports are still sent, they are not link-able to each other

I now understand the leak of information. I missed this part in the proposal, I thought that "negative" reports (with an attribution_credit of 0) of a user would still be linked somehow with the "positive" report (with an attribution_credit of 100) in case of a conversion, if they fall within the same reporting window.

This is actually critical I think for adtech companies to be able to train models. Implicitly or explicitly most ML model in this field learn on "user timelines" of events, so if all reports are completely unlink-able to each other this will almost surely erase a lot of the signal that is learned today.

I suppose this is done in order to prevent abusers from using error correcting codes, but is it really a deal breaker in terms of privacy if reports can be linked between each other?

**Comment by johnivdel** [comment]
The API has changed quite a bit since this issue was filed, discussed. For example, we now support flexible attribution schemes through priority, as well as filter based attribution. 

Will mark this issue as closed, if there are still any issues here, please feel free to re-open this issue / file a new one.
