### ISSUE TITLE
Consider consolidating headers into one for sources, one for triggers

### ISSUE THREAD

**Issue by apasel422** [WICG/attribution-reporting-api#432]
Currently, sources are registered via the combination of two separate headers: `Attribution-Reporting-Register-Source` and `Attribution-Reporting-Register-Aggregatable-Source`, the latter of which is optional.

Triggers are registered by the combination of five separate ones: `Attribution-Reporting-Register-Event-Trigger`, `Attribution-Reporting-Trigger-Debug-Key`, `Attribution-Reporting-Filters`, `Attribution-Reporting-Register-Aggregatable-Trigger-Data`, `Attribution-Reporting-Register-Aggregatable-Values`, all but the first of which are optional.

All of these headers contain JSON other than `Attribution-Reporting-Trigger-Debug-Key`, which contains a single integer formatted as a base-10 string.

These headers have rather verbose names and must be generated and parsed separately. Future features would probably require adding additional headers, especially for the existing headers whose top-level type is a JSON list.

Instead, we could consolidate these headers into one for source registration and one for trigger registration.

For sources, we could extend the existing dictionary used by `Attribution-Reporting-Register-Source` with an optional field corresponding to the `Attribution-Reporting-Register-Aggregatable-Source` header, which would be removed.

For triggers, we could replace the five existing headers with a single new one called `Attribution-Reporting-Register-Trigger` whose value would be a dictionary like:

```jsonc
{
  "event_trigger_data": [...], // same format as Attribution-Reporting-Register-Event-Trigger header
  "debug_key: "...", // optional; same format as Attribution-Reporting-Trigger-Debug-Key header
  "filters": {...}, // optional; same format as Attribution-Reporting-Filters header
  "aggregatable_trigger_data": [...], // optional; same format as Attribution-Reporting-Register-Aggregatable-Trigger-Data header
  "aggregatable_values: {...} // optional; same format as Attribution-Reporting-Register-Aggregatable-Values header
}
```

**Comment by csharrison** [comment]
Yes there are a number of benefits for doing this, and very little cost. The existing situation has:
- Implementation considerations of invoking a (possibly cross process) JSON parser multiple times.
- Bandwidth considerations of shipping many verbose header names
- Complexity due to everything not being in one structure

We originally did this out of the hope of using structured headers, where reducing one level of nesting was a big benefit. However, we didn't end up going with structured headers and so there isn't much benefit of bringing along that baggage. See https://github.com/WICG/conversion-measurement-api/issues/194 which we probably need to update with the decision.
