### ISSUE TITLE
Conversions coming from a different domain than landing page

### ISSUE THREAD

**Issue by jinghao** [WICG/attribution-reporting-api#44]
Hi @csharrison and @michaelkleber !

## Context

In past W3C web-adv calls, we've discussed the case where conversions come from a different domain than the landing page's domain. This could happen for a number of reasons--localized websites (i.e. shop.com taking you to shop.co.uk), commerce platforms (i.e. my-store.com taking you to my-store.shopify.com) or others (i.e. gap.com taking you to gapfactory.com).

My understanding is that the current draft specification would lose the conversion. From the calls, it seems that people believe this is a legitimate use case, so I'm eager to work with you all to come up with a privacy-safe way of supporting this use case.

I'm not attached to any particular solution if we can solve these problems, but to kick off the discussion, here are a few thoughts:

## Delegation of trust

This could be either implicit or explicit. When my-store.com (the "landing page domain") takes you to my-store.shopify.com (the "destination domain"), it could be annotated (in the anchor tag or redirect) that it's delegating the reporting permissions to the destination. When conversions finally happen on the destination domain, they are reported to the publisher as if they came from the landing page domain. 

This introduces more complexity because the browser has to track the pathway to the conversion. I don't think this requires significant amounts of new data but I appreciate that it has its costs.

Do people see privacy concerns with this?

## Support of multiple domains in the original ad annotation

Instead of listing just one domain, perhaps the publisher can list multiple domains. There would have to be some limit to the number of domains, with perhaps an exception for country-level TLD variations. This could also be used in conjunction with the above proposal to add more protections, so that both the publisher side and the advertiser side need to certify the delegation.

## Quick-redirect through the conversion domain

This was brought up by @csharrison during a call. It has a few downsides:

1. It presumes that the publisher knows where the conversion will happen. This is the case for commerce platforms but not the case for multi-national domains.
2. It adds another redirect overhead to the initial page load, which is a bad user experience
3. I'm not sure that it's compatible with PCM's privacy model. My understanding is that the ad must land on the `adDestination` domain, not merely traverse through it. 

## Next steps

How do we move this discussion forward? Are there other ideas for addressing this major use case without compromising privacy? I'm open to feedback on how we could build upon or improve any of the ideas above, or any other ones that can solve this problem.

Thanks!

**Comment by csharrison** [comment]
Let me begin by reviewing the privacy challenges I mentioned on the web-adv calls. In the existing API, given an ad click to ad.com, the publisher / SSP knows the user is browsing ad.com (i.e. this piece of user browsing history is impossible to hide). The event level conversion API reveals a small amount of ad.com activity _given_ that we know the user browsed ad.com. When we start allowing conversions to happen on domains other than ad.com (e.g. sensitive.com), the existence of a conversion report reveals some extra information that the user actually visited sensitive.com in the first place.

This is a problem with the "Support of multiple domains in the original ad annotation" idea if implemented alone. Additionally there is a more nebulous challenge of user expectations, as activity on sensitive.com is more divorced from publisher.com.

The natural way to resolve some of these issues is to either:
- Have some way of declaring sensitive.com and ad.com to be the "same party". This would probably use something like [First Party Sets](https://github.com/krgovind/first-party-sets). Conversion reports will then target an entire FPS.
- Introduce an ad-hoc way of ensuring that the revealed information is in some way "equivalent" to the existing API. I think this is what the "delegation of trust" idea tries to do, as well as the quick-redirect idea.

For the "delegation" idea: If the landing page needs to annotate e.g. outgoing navigations with delegation of measurement, then the advertiser certainly knows that leg of the user's browsing history and could always fire off a conversion on its own, revealing that link. However, it is not exactly equivalent to the existing information because now conversion reports can be based on a mixture of two first parties' notion of your user identity (ad.com or sensitive.com). This still seems in some ways non-ideal, though maybe tolerable. This is mitigated by new annotations in the impression that designate a fixed single converting domain though.

I think (though I’m not 100% sure) that we can make this delegation work, though it may end up being messy. Do you think an integration of FPS could work in this case? It is definitely cleaner and seems to work for all your examples, but I think it falls apart if there is some generic “conversion service” that wants to register conversions for lots of entities (this case may be possibly handled by heavy use of the PSL though).

**Comment by jinghao** [comment]
Thank you for the detailed explanation!

I completely understand the privacy challenges you described, especially with the "Support of multiple domains in the original ad annotation" idea. I didn't expect it to be used alone, but perhaps in conjunction with the delegation idea to make it more water-tight. 

Moreover, I also understand that we have to weigh the complexity trade-offs.

In terms of how delegation would work, I anticipate something similar to [what you proposed for delegation of conversion measurement to a cross-origin iframe](https://github.com/WICG/conversion-measurement-api#conversion-registration).

As for requiring new annotations to designate a fixed single converting domain, it would solve the problem but introduce more complexity for advertisers to grapple with when creating/managing their ads. The marketer running the campaigns are usually not as technical as the developers so to require them to enter two URLs (my-shop.com and shopify.com) into the correct boxes will introduce a lot more confusion/friction that I'd like to avoid if possible. Of course, it's still better than losing those conversions entirely. Given that, I'd like to understand how bad is the concern of conversions being based on a mixture of two domains. When the conversion report comes in, as long as the domain is always `ad.com`, and we don't tell the publisher which domain it actually came from, would that help things?

As for FPS, I did look at that in the past and while it has a lot of nice properties, I also have many concerns about using it here:

- It's a significant part of the internet infrastructure to establish, with a complex certification system, uncertain timelines, and just in general more stuff for advertisers to wrangle with. Perhaps this would work for the multi-nationals with sophisticated tech teams and domains for each country they serve, but definitely not for the businesses that rely on platforms like shopify.com
- On top of the complexity, FPS is also a "set", i.e. undirected. I think in this case of a common platform shared by multiple businesses, it would have to be directed in some way. Delegation is what enables that. One difference here is that the annotation is in the redirect or link, whereas for FPS it's in some JSON manifest.

So I would love for us to be able to support measurement delegation if we can without introducing significant complexity or friction to the advertisers. Naturally, I am more concerned about complexity there than in the APIs that developers have to leverage. 

Thanks again for your input. Glad to hear that there's a path forward! Looking forward to your thoughts.

**Comment by csharrison** [comment]
Hey Jing,
> Given that, I'd like to understand how bad is the concern of conversions being based on a mixture of two domains. When the conversion report comes in, as long as the domain is always ad.com, and we don't tell the publisher which domain it actually came from, would that help things?

It doesn't seem _that_ bad to me, but it relies on complexity around navigation tracking on the landing page which is non-ideal for complexity reasons. The API already is fairly complex with requirements on navigation from ad --> landing page which required significant work implementation-wise.

In terms of API surface, I think Feature-Policy is not a great fit because we aren't delegating permission into an iframe, we are propagating permission across a navigation. Maybe some similar could work though, we'd need to think it through.

> As for FPS, I did look at that in the past and while it has a lot of nice properties, I also have many concerns about using it here

These concerns make sense to me, it seems like FPS is not a good solution for the use-case of a common platform shared by multiple businesses. I also see the problems with adoption cost, though possibly they could be mitigated in some way.

I will continue to think through this issue but I have a general question: can you explain in more details why redirecting to a third party conversion provider is necessary from a technical point of view? I wonder why these providers aren't embedded in the advertiser page in the first place. I understand that it would probably be a large re-architecture, but I am wondering if there is anything concrete we lose by doing this.

**Comment by jinghao** [comment]
> It doesn't seem that bad to me, but it relies on complexity around navigation tracking on the landing page which is non-ideal for complexity reasons. The API already is fairly complex with requirements on navigation from ad --> landing page which required significant work implementation-wise.

Got it. I understand the implementation will be more complex but the API should be roughly the same except the delegation annotation. Right? 

> In terms of API surface, I think Feature-Policy is not a great fit because we aren't delegating permission into an iframe, we are propagating permission across a navigation. Maybe some similar could work though, we'd need to think it through.

Sure, I didn't mean literally Feature-Policy, just something like it.

> These concerns make sense to me, it seems like FPS is not a good solution for the use-case of a common platform shared by multiple businesses. I also see the problems with adoption cost, though possibly they could be mitigated in some way.

Thanks for understanding!

> I will continue to think through this issue but I have a general question: can you explain in more details why redirecting to a third party conversion provider is necessary from a technical point of view? I wonder why these providers aren't embedded in the advertiser page in the first place. I understand that it would probably be a large re-architecture, but I am wondering if there is anything concrete we lose by doing this.

I'm not sure if I can fully represent why that's necessary or if it's even necessary. I'm just observing from the analysis and research we've done that it's a very common pattern. Perhaps there is a future in which all of these "conversion platforms" become embedded in the original website, and some verifiable trust symbol is displayed from the conversion platform. I'm much more likely to input my credit card on PayPal or Shopify domains than on random-store.com. This is on top of the obvious costs of rearchitecting everything. I'm open to discussing that as a long term idea but I just don't think that'll have alignment much less material adoption, before we want to adopt the conversion measurement API.

Hope that makes sense. Thanks for engaging--I'm hopeful we can get to a clean solution to these problems!
