### ISSUE TITLE
Question for Multi-touch scenarios

### ISSUE THREAD

**Issue by Mingyang-ZH** [WICG/attribution-reporting-api#65]
Hi teams, I have a few questions regarding to this multi-touch scenarios:
1. "The default attribution model will be last-click attribution, giving the last-clicked impression for a given conversion event all of the credit." can we confirm this last-click attribution is finalized by default? If we choose this approach, does that means the last impression take attribution credit 100 and rest of them are 0?

2. "If multiple impressions were clicked and led to a single conversion, send conversion reports for all of them."
According to the delay window, all the events in the same report will be sent at the same time(same window), wondering how long is this time range? In 5 mins or in 10 mins? or it depends on how many events we have? Cause we need to set up some timer at downstream.

3. "To provide additional utility, the browser can choose to provide additional annotations to each of these reports, attributing credits for the conversion to them individually. "  Do we have more clarification on how to do the annotations?

Thanks for help!

**Comment by csharrison** [comment]
1. I wouldn't say "finalized" since this API is still under development but yes this is how attribution works in Chrome's current implementation. With this approach  the last impression takes credit 100 and the rest are 0.

2. The reports for different impressions are sent independently via their own schedule. See the algorithm here for more details:
https://github.com/WICG/conversion-measurement-api#sending-scheduled-reports

The idea is that we explicitly don't want multi-touch impressions to be associated with each other especially in cases where they occur on separate sites.

3. The annotations here refer to the "attribution-credit" field i.e. the 100 or 0 values for credit.

**Comment by Mingyang-ZH** [comment]
Thanks for your reply, I think answer 1 and 3 are very clear for me, just a little follow on 2:

According to the proposal, we have 2 or 3 conversion reporting window, but how long is the range? for example, 2 days minus 1 hour: seems like a timestamp for me, not a time range（let's say 5 mins or one hour). Also, for corner cases, like same ad clicked twice leading to same conversion in the same site, I'm assuming we will receive two impressions with latter one attribution credit 100 and first one 0?  If that's the case, can we do downstream dedup based on attribution credit value?

**Comment by csharrison** [comment]
Hey @Mingyang-ZH , the proposal has changed quite a bit since this issue so I'm going to close this out. In particular, we no longer support sending "0" credit reports, and we will only ever attribute a single source to a particular trigger / conversion. I think this simplifies the handling of multiple impressions.
