### ISSUE TITLE
New Reporting Origin Rate Limit

### ISSUE THREAD

**Issue by akashnadan** [WICG/attribution-reporting-api#725]
We are considering adding the following reporting origin rate limit: 1 reporting origin per {source site, reporting site}

[Site](https://html.spec.whatwg.org/multipage/browsers.html#site) = eTLD + 1

This change would have a positive impact on privacy and help prevent some potential attacks i.e. ad techs using multiple reporting origins to achieve additional privacy budget.

We are looking for feedback on if this change puts any use-cases at risk.

**Comment by dmdabbs** [comment]
I'm not grokking your 'reporting site' reference. 

There is _reporting origin_ that must be identical across Source and Trigger registration responses, correct? IOW, https://ara.advertiser.example on both sides.

_Destination site_, the one to three eTLD+1s extracted from the `destination` value(s) at source registration.

And _source site_, the eTLD+1 where the source is registered.

**Comment by csharrison** [comment]
@dmdabbs if I understand correctly, this is about restricting the number of _origins_ a given _site_ can use as reporting endpoints, on one source site. That is, in the following sequence:
1. a.adtech.example registers a source on publisher.com
2. b.adtech.example registers a source on publisher.com

(2) would be disallowed by this new rate-limit, because the reporting endpoint's _site_ (adtech.example) has already had one origin register on publisher.com.

**Comment by dmdabbs** [comment]
@csharrison thank you for the clarification!
I certainly understand the need to head adtech privacy budget attacks off at the pass. 

One use case for which this might produce friction is a multi-brand CPG or other entity using the same origin for various 'product lines' conversions. The advertiser or their partner will need to use separate reporting origins for each in order to create separate 'attribution lanes' for each line. Those lines would no longer have use of linea.advertiser.com, brandb.advertiser.com &c.

**Comment by csharrison** [comment]
> One use case for which this might produce friction is a multi-brand CPG or other entity using the same origin for various 'product lines' conversions. The advertiser or their partner will need to use separate reporting origins for each in order to create separate 'attribution lanes' for each line. Those lines would no longer have use of linea.advertiser.com, brandb.advertiser.com &c.

Thanks for the feedback! We hoped to solve this in some way with the [attribution filtering mechanism](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#optional-attribution-filters), but this doesn't quite support multiple independent lanes like multiple reporting origins does. The filtering mechanism just lets you selectively ignore conversions that attribute to the wrong category/lane.

The problem with wholey supporting this use-case is that unfortunately it can lead to unintuitive privacy violations.
