### ISSUE TITLE
Consider making Attribution-Reporting-Eligible header usage consistent across HTML tags and request APIs

### ISSUE THREAD

**Issue by arpitjainx** [WICG/attribution-reporting-api#756]
As per the AR API [spec](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#registering-attribution-sources), for `<a>`, `<img>` and `<script>` tags and `window.open()` calls, the `Attribution-Reporting-Eligible` header is added by the browser when the `attributionsrc` attribute/feature is present and the browser considers the source or the trigger to be eligible for API registration. In contrast, for request APIs such as `window.fetch()` and `XMLHttpRequest` the header needs to be manually added by the publisher / ad tech. This doesn't really give an indication of whether the browser actually considers the event to be eligible for AR API registration.

During Chrome's Origin Trial, the presence of the header has been a useful signal for identifying integration issues and other bugs such as the publisher not rendering the correct Origin Trial token and Chrome on Android not considering new tab clicks eligible for registration: [crbug.com/1394437](http://crbug.com/1394437). This header would be useful for identifying similar issues with events registered using the `window.fetch()` and `XMLHttpRequest` APIs if the browser could be instructed to itself add the header when it considers the event to be eligible for AR API registration.

Also to note is that manually adding the `Attribution-Reporting-Eligible` header to these request APIs appears to trigger [CORS preflight requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) which doubles(?) the incoming QPS and requires additional work from the ad tech to handle them.

**Comment by apasel422** [comment]
Thanks for posting this. @csharrison posted something similar at https://github.com/WICG/attribution-reporting-api/issues/540#issuecomment-1349644201. I agree that the discrepancy between the API surfaces in this regard is non-ideal.

I don't know how hard it would be to add first-class support for Attribution Reporting to `XmlHttpRequest`, but at least for `fetch`, we could add a field to [`RequestInit`](https://fetch.spec.whatwg.org/#requestinit) corresponding to the eligibility, defaulting to `trigger`.

If we removed manual setting of the `Attribution-Reporting-Eligible` header, we could also [consider merging it](https://github.com/WICG/attribution-reporting-api/issues/540#issuecomment-1216687382) with `Attribution-Reporting-Support`: we chose separate headers is because one was user-specified for `fetch` and one was always browser-specified.

**Comment by jfggit** [comment]
Given that #757 was merged, can we definitively say that we're committed to this change to the API and that it's coming in the future? Also could we get confirmation on whether the CORS preflight is no longer needed?

**Comment by csharrison** [comment]
Yes we intend to make this change in the API. @apasel422 for preflight details. I think this is the first step to removing the preflight but in the Chromium implementation there are a few other refactors we need to do to get rid of them completely.

**Comment by jfggit** [comment]
Just want to confirm that a reasonable migration strategy for this is:

1. Implement the new first-class option with fetch calls that meant to register event/trigger sources, while leaving the header setting behavior in place also (to maintain support until the new first-class option is widely available).
2. Remove direct header setting at some future date once first-class option is ubiquitous.
3. Move to no-cors mode at some further future date once that has been officially announced and released.

Specifically, doing both things in step 1 is safe both before and after the new registration method is enabled, right?

**Comment by apasel422** [comment]
> 1. Implement the new first-class option with fetch calls that meant to register event/trigger sources, while leaving the header setting behavior in place also (to maintain support until the new first-class option is widely available).
> 2. Remove direct header setting at some future date once first-class option is ubiquitous.

You can feature-detect the new API surface with the following, or equivalent:

```js
if ('setAttributionReporting' in XMLHttpRequest.prototype) {
  xhr.setAttributionReporting({eventSourceEligible: true, triggerEligible: false});
} else {
  xhr.setRequestHeader('Attribution-Reporting-Eligible', 'event-source');
}
```

`fetch`'s support can't be directly detected due to the use of a dictionary option, but at least for Chromium the `fetch` and XHR changes landed simultaneously, so successful detection on XHR implies support on `fetch`.

> 3. Move to no-cors mode at some further future date once that has been officially announced and released.

Correct.

**Comment by jfggit** [comment]
Ok, so feature detection is doable, but is it necessary? Specifically, if I use the new dictionary option with fetch *and* also set the header manually, are the following true:

1. Prior to the changeover, setting the new attributionReporting dictionary option is harmless and has no effect on the header option which will continue to work as they do currently.

2. After the changeover, setting the Attribution-Reporting-Eligible header will be ignored and only the attributionReporting option will affect whether the request contains headers and is eligible for registration (along with the API actually being available).

**Comment by apasel422** [comment]
> 1. Prior to the changeover, setting the new attributionReporting dictionary option is harmless and has no effect on the header option which will continue to work as they do currently.

Yes, it is harmless.

> 2. After the changeover, setting the Attribution-Reporting-Eligible header will be ignored and only the attributionReporting option will affect whether the request contains headers and is eligible for registration (along with the API actually being available).

Yes.

But it seems to me that if you're going to the trouble of "us[ing] the new dictionary option with fetch *and* also set[ting] the header manually", you might as well use actual feature detection.

**Comment by jfggit** [comment]
@apasel422 Given that this issue is closed, is there somewhere to specifically track the progress of the removal of CORS preflight requirements?

**Comment by apasel422** [comment]
> @apasel422 Given that this issue is closed, is there somewhere to specifically track the progress of the removal of CORS preflight requirements?

IIUC there is nothing in the spec that requires this, only the current Chromium implementation, so please file a bug using [the Internals>Attribution Reporting component](https://bugs.chromium.org/p/chromium/issues/list?q=component:Internals%3EAttributionReporting).

**Comment by jfggit** [comment]
Hmm, actually trying it now in Chrome 114 with the new dictionary option, it seems to allow for mode: 'no-cors' as a setting with no apparently downsides (no preflight happens and Attriubution-Reporting-Eligible header is present). Is it safe to assume (at least for 114+) that the CORS requirement is no longer an issue? Happy to create a Chromium bug if needed otherwise.
